class Constants:

    EDIT_TEXT = "EditText"
    CENTRAL_WIDGET = "centralwidget"
    GRID_LAYOUT = "gridLayout"
    VERTICAL_LAYOUT = "verticalLayout"
    TEXT = "Text"
    HORIZONTAL_LAYOUT = "horizontalLayout"
    WORDS = "words"
    LETTERS = "letters"
    LABEL = "label"
    MENU_BAR = "menubar"
    MENU_FILE = "menuFile"
    MENU_TOOL = "menuTool"
    STATUSBAR = "statusbar"
    ACTION_NEW = "actionNew"
    ACTION_OPEN = "actionOpen"
    ACTION_CLOSE = "actionClose"
    ACTION_SAVE = "actionSave"
    ACTION_TEXT_COLOR = "actionTextColor"
    ACTION_BACKGROUND_COLOR = "actionBackgroundColor"
    ACTION_FONT_SIZE = "actionSizeFont"
    ASK_RESTORE_DATA = "Do you want to restore data?"
    ASK_YOU_SURE = "You sure?"
    ERROR_CAN_NOT_OPEN_FILE = "Can not open file"
    CANCELED = "Canceled"
    CHANGE_SIZE = "Change size"
    PERCENTAGE = "Percentage"
